export const SEARCH_GNOMES_START = "SEARCH_GNOMES_START";
export const SEARCH_GNOMES_COMPLETE = "SEARCH_GNOMES_COMPLETE";
export const SEARCH_GNOMES_ERROR = "SEARCH_GNOMES_ERROR";

export const SEARCH_GNOMES_BY_ID = "SEARCH_GNOMES_BY_ID";
export const SEARCH_GNOMES_BY_ID_COMPLETE = "SEARCH_GNOMES_BY_ID_COMPLETE";
export const SEARCH_GNOMES_BY_ID_ERROR = "SEARCH_GNOMES_BY_ID_ERROR";
